<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Communication\RKWorkspace.Transport.NamedPipes\RKWorkspace.Transport.NamedPipes.csproj" />
    <ProjectReference Include="..\..\..\src\Communication\RKWorkspace.Transport\RKWorkspace.Transport.csproj" />
    <ProjectReference Include="..\..\..\src\Core\RKWorkspace.Core.csproj" />
  </ItemGroup>
</Project>
