<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Communication\RKWorkspace.RkwpTransport.SecureDev\RKWorkspace.RkwpTransport.SecureDev.csproj" />
    <ProjectReference Include="..\..\Protocol\RKWorkspace.Protocol\RKWorkspace.Protocol.csproj" />
  </ItemGroup>
</Project>
