$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$exportRoot = Join-Path $root 'release\codex-context'
$staging = Join-Path $env:TEMP "RKWorkspace_Context_$timestamp"
$zipPath = Join-Path $exportRoot "RKWorkspace_Context_$timestamp.zip"
$latestZipPath = Join-Path $exportRoot 'RKWorkspace_Context_latest.zip'

New-Item -ItemType Directory -Path $exportRoot -Force | Out-Null
Remove-Item -LiteralPath $staging -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $staging -Force | Out-Null

function Copy-ContextFile {
    param(
        [Parameter(Mandatory = $true)]
        [string] $RelativePath
    )

    $source = Join-Path $root $RelativePath
    if (-not (Test-Path $source)) {
        return
    }

    $target = Join-Path $staging $RelativePath
    New-Item -ItemType Directory -Path (Split-Path -Parent $target) -Force | Out-Null
    Copy-Item -LiteralPath $source -Destination $target -Force
}

$files = @(
    'README.md',
    'Docs\README.md',
    'Docs\Nordstern.md',
    'Docs\Glossary.md',
    'Docs\WorkspaceShell.md',
    'Docs\Architecture\README.md',
    'Docs\GlassEdgeNearestAblage.md',
    'Docs\AblageProximityAndDistance.md',
    'Docs\Proximity\ManualAblageMap.md',
    'Docs\Proximity\BleDiscoverySpike.md',
    'Docs\Proximity\WiFiPresenceProvider.md',
    'Docs\Proximity\UwbRequirements.md',
    'Docs\Proximity\UWB_PrivacyConsent.md',
    'Docs\Proximity\SensorFusionRoadmap.md',
    'Docs\Proximity\EdgeSelectionUserControl.md',
    'Docs\AblageAnchorDongle.md',
    'Docs\Hardware\AblageAnchorDongle_MVP.md',
    'Docs\Hardware\DongleFirmwareArchitecture.md',
    'Docs\Hardware\UsbDongleControlProtocol.md',
    'Docs\GestureStrategy.md',
    'Docs\Roadmap\RKWorkspace_Roadmap.md',
    'Docs\Development\WindowsLocalFrameE2E.md',
    'Docs\Development\GlassEdgePdfFrameE2E.md',
    'Docs\Development\PdfFrameInteraction.md',
    'Docs\Development\RKWP_Diagnostics.md',
    'Docs\Development\OwnerGuestFrameStateUX.md',
    'Docs\Development\ManualMapStudioUiPlan.md',
    'Docs\Development\DiagnosticsDashboardPlan.md',
    'Docs\Development\CrossPlatformCIPlan.md',
    'Docs\Protocol\RKWP_ProtocolFoundation.md',
    'Docs\Protocol\RKWP_SecurityModel.md',
    'Docs\Protocol\RKWP_SecureSession.md',
    'Docs\Protocol\RKWP_AblageIdentityAndTrust.md',
    'Docs\Protocol\RKWP_Pairing.md',
    'Docs\Protocol\RKWP_TransportProfiles.md',
    'Docs\Protocol\RKWP_DevTransport.md',
    'Docs\Protocol\RKWP_OwnershipAndLease.md',
    'Docs\Protocol\RKWP_FrameSession.md',
    'Docs\Protocol\RKWP_InputChannel.md',
    'Docs\Protocol\RKWP_ChangeSetAndReturn.md',
    'Docs\Protocol\RKWP_ObjectKindRules.md',
    'Docs\Protocol\RKWP_OwnershipTransfer.md',
    'Docs\Protocol\RKWP_PlatformStrategy.md',
    'Docs\Protocol\RKWP_EmergencyReturn.md',
    'Docs\Protocol\RKWP_ProductTransportPlan.md',
    'Docs\Protocol\RKWP_OfflineReconnectStrategy.md',
    'Docs\Protocol\RKWP_NetworkQualityAdaptation.md',
    'Docs\Policy\RKWP_PolicyProfiles.md',
    'Docs\Policy\PolicyEditorPlan.md',
    'Docs\Performance\RKWP_PerformanceBaseline.md',
    'Docs\Performance\PdfFramePerformance.md',
    'Docs\Performance\E2EPerformanceBaseline.md',
    'Docs\Performance\LatencyOptimizationNotes.md',
    'Docs\Performance\MemoryProfilingPlan.md',
    'Docs\Performance\MobileBatteryPerformancePlan.md',
    'Docs\Performance\FrameCompressionStrategy.md',
    'Docs\Performance\PerformanceDashboardPlan.md',
    'Docs\Security\RKWP_SecurityGate.md',
    'Docs\Security\RKWP_DevCertificates.md',
    'Docs\Security\RKWP_SecureSessionPath.md',
    'Docs\Security\AblageIdentityStore.md',
    'Docs\Security\RKWP_CryptoDecision.md',
    'Docs\Security\RKWP_MutualAuthenticationModel.md',
    'Docs\Security\RKWP_CertificateProvisioning.md',
    'Docs\Security\RKWP_SecretsStorageByPlatform.md',
    'Docs\Security\AblageIdentityBackupRestore.md',
    'Docs\Security\CodeSigningPlan.md',
    'Docs\Security\RendererSandboxModel.md',
    'Docs\ADR\README.md',
    'Docs\ADR\ADR_MA016_OriginalOwnedPdfLifecycle.md',
    'Docs\ADR\ADR_MA016_ProximityFusion.md',
    'Docs\Audit\RKWP_AuditTamperResistance.md',
    'Docs\Audit\LogRetentionAndRedactionPolicy.md',
    'Docs\UX\AblagePairingExperience.md',
    'Docs\UX\GlassEdgeAfterFrameFlow.md',
    'Docs\UX\DigitalHandForRealObjects.md',
    'Docs\UX\OwnerGuestFrameStateMachine.md',
    'Docs\UX\InteractionTimingLab.md',
    'Docs\UX\AccessibilityAndNonIntrusiveOverlay.md',
    'Docs\UX\FrameErrorExperience.md',
    'Docs\HumanExperience\OriginalOwnedFrameTestHarness.md',
    'Docs\HumanExperience\OwnerFeedbackLog_MA013.md',
    'Docs\HumanExperience\MA016_PilotFeedbackTaxonomy.md',
    'Docs\HumanExperience\MA016_RedYellowGreenCriteria.md',
    'Docs\HumanExperience\MA016_PilotInterviewGuide.md',
    'Docs\HumanExperience\MA016_TrustQuestions.md',
    'Docs\HumanExperience\MA016_RecoveryFeelingTest.md',
    'Docs\HumanExperience\MA016_iPadHapticFeelingTest.md',
    'Docs\HumanExperience\MA016_ProximityFeelingTest.md',
    'Docs\HumanExperience\MA016_ClosedOpenPdfFeelingComparison.md',
    'Docs\HumanExperience\MA016_HumanExperienceSummary.md',
    'Docs\ObjectAdapters\WindowsObjectAdapters.md',
    'Docs\ObjectAdapters\AppWindowInteractiveFrame.md',
    'Docs\ObjectAdapters\BrowserTabStrategy.md',
    'Docs\ObjectAdapters\EmailDraftAdapterRoadmap.md',
    'Docs\Readiness\MA007_ReadinessReview.md',
    'Docs\Readiness\MA009_ReadinessReview.md',
    'Docs\Readiness\MA009_RealLabTestPlan.md',
    'Docs\Readiness\MA009_NextCodexActions.md',
    'Docs\Readiness\MA010_ReadinessReview.md',
    'Docs\Readiness\MA010_PilotTestPlan.md',
    'Docs\Readiness\MA010_NextPlatformCodexActions.md',
    'Docs\Readiness\MA011_ReadinessReview.md',
    'Docs\Readiness\MA011_WindowsToMac_FirstRealTest.md',
    'Docs\Readiness\MA011_iPad_FirstRealTest.md',
    'Docs\Readiness\MA011_NextCodexActions.md',
    'Docs\Readiness\WindowsToMac_FirstRealTestGate.md',
    'Docs\Readiness\WindowsToiPad_FirstRealTestGate.md',
    'Docs\Readiness\iOS_MA013_ReadinessGate.md',
    'Docs\Readiness\MA013_SecurityReadinessGate.md',
    'Docs\Readiness\PdfFrameRendererReadiness.md',
    'Docs\Readiness\ObjectAdapterReadiness.md',
    'Docs\Readiness\ProximityReadiness.md',
    'Docs\Readiness\UXReadiness_OriginalOwnedFrame.md',
    'Docs\Readiness\OperationsReadiness.md',
    'Docs\Readiness\InstallReadiness.md',
    'Docs\Readiness\PilotAcceptanceCriteria.md',
    'Docs\Readiness\MA013_ReadinessReview.md',
    'Docs\Readiness\MA013_RealPilotStartPlan.md',
    'Docs\Readiness\MA013_NextCodexActions.md',
    'Docs\Readiness\MA016_TargetState.md',
    'Docs\Readiness\MA016_TestMatrix.md',
    'Docs\Readiness\MA016_GoNoGoCriteria.md',
    'Docs\Readiness\MA016_PilotRoles.md',
    'Docs\Readiness\MA016_StartCheckpoint.md',
    'Docs\Readiness\MA016_WindowsPdfLifecycleCheckpoint.md',
    'Docs\Readiness\MA016_NoFileIngressSecurityCheckpoint.md',
    'Docs\Readiness\MA016_macOSReadinessCheckpoint.md',
    'Docs\Readiness\MA016_iOS_iPadReadinessCheckpoint.md',
    'Docs\Readiness\MA016_UWBProximityCheckpoint.md',
    'Docs\Readiness\MA016_SecurityPolicyCheckpoint.md',
    'Docs\Readiness\MA016_PilotLabCheckpoint.md',
    'Docs\Readiness\MA016_ReadinessReview.md',
    'Docs\Readiness\MA016_GoNoGoDecision.md',
    'Docs\Readiness\MA016_FullVerification.md',
    'Docs\Readiness\MA016_FinalVerificationPlan.md',
    'Docs\Readiness\MA016_CompletionReport.md',
    'Docs\Readiness\MA016_FollowupCheckpoint.md',
    'Docs\Readiness\MA017_TargetState.md',
    'Docs\Readiness\MA017_PilotMatrix.md',
    'Docs\Readiness\MA017_GoNoGoCriteria.md',
    'Docs\Readiness\MA017_PlatformStatus.md',
    'Docs\Readiness\MA017_StartCheckpoint.md',
    'Docs\Readiness\MA017_WindowsPilotCheckpoint.md',
    'Docs\Readiness\MA017_SecurityPolicyPilotCheckpoint.md',
    'Docs\Testing\MA016_macOS_FirstPilotRunbook.md',
    'Docs\Testing\MA016_iOS_USBInstallRunbook.md',
    'Docs\Testing\MA016_CrossDeviceOwnerInstructions.md',
    'Docs\Testing\MA016_CrossDeviceFailurePlaybook.md',
    'Docs\Testing\MA016_SecurityOwnerChecklist.md',
    'Docs\Testing\MA016_RealTestRunbook.md',
    'Docs\Testing\MA017_OwnerTestGoal.md',
    'Docs\Testing\MA017_WindowsPdfStandardTest.md',
    'Docs\Security\MA017_PdfLifecycleThreatModel.md',
    'Docs\Readiness\CrossDeviceTestPlan_Windows_macOS_iPad.md',
    'Docs\Readiness\WindowsToMac_DevTransportPlan.md',
    'Docs\Readiness\WindowsToMac_LanTestPlan.md',
    'Docs\Readiness\iPad_iPhone_Surface_TestPlan.md',
    'Docs\Readiness\NextCodexActions.md',
    'Docs\Platform\macOS_SurfaceStarterKit.md',
    'Docs\Platform\macOS_RepositoryBootstrap.md',
    'Docs\Platform\macOS_FrameGuestUI.md',
    'Docs\Platform\macOS_NoFileIngressChecklist.md',
    'Docs\Platform\macOS_ReturnAndRecovery.md',
    'Docs\Platform\macOS_FrameRenderingStrategy.md',
    'Docs\Platform\macOS_DevAgentPackaging.md',
    'Docs\Platform\macOS_GestureAndGlassEdge.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\README.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-project-layout.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-rkwp-client-flow.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-rkwp-client-architecture.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-rkwp-message-flow.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-rkwp-devtransport-client.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-rkwp-securedev-client.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-frame-guest-ui.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-frame-guest-ui-spec.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-permissions-checklist.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-build-commands.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macos-test-plan.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macOS_FrameGuestSurface_Design.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macOS_Permissions_Checklist.md',
    'src\Surfaces\RKWorkspace.Surface.macOS\macOS_Build_Notes.md',
    'release\ma016\handoff\macOS_START_HERE.md',
    'release\ma016\handoff\macOS_MinimalGuestAppTask.md',
    'release\ma016\handoff\macOS_ReturnRecovery_UXContract.md',
    'release\ma016\handoff\macOS_FINAL_HANDOFF.md',
    'release\ma016\handoff\macOS_NEXT_REAL_IMPLEMENTATION_TASK.md',
    'release\ma016\config\macos-guest.sample.json',
    'release\ma016\schemas\macos-capsule-contract.v0.1.json',
    'release\ma016\schemas\macos-openframe-contract.v0.1.json',
    'release\ma016\schemas\macos-no-file-ingress-contract.v0.1.json',
    'release\ma016\reports\no-file-ingress-report.md',
    'release\ma016\reports\cross-device-diagnostics.md',
    'release\ma016\reports\cross-device-audit-events.md',
    'release\ma016\reports\ma016-pilot-report.md',
    'release\ma016\reports\ma016-feedback-report.md',
    'release\ma016\reports\ma016-repeatability-report.md',
    'release\ma016\reports\ma016-performance-baseline.md',
    'release\ma016\reports\REPOSITORY_HYGIENE.md',
    'release\ma016\FINAL_VERIFICATION.md',
    'release\ma016\GO_NO_GO.md',
    'release\ma016\PILOT_START_RECOMMENDATION.md',
    'release\ma016\OWNER_SHORT_GUIDE.md',
    'release\ma016\PLATFORM_HANDOFF_SUMMARY.md',
    'release\ma016\reports\templates\no-file-ingress-macos-template.md',
    'release\ma016\packages\apple-rkwp-bundle\README.md',
    'release\ma016\packages\apple-rkwp-bundle\swift-model-plan.md',
    'release\ma016\packages\apple-rkwp-bundle\schemas\rkwp-frame-capsule-v0.1.schema.json',
    'release\ma016\packages\apple-rkwp-bundle\samples\capsule-open-sequence.json',
    'release\ma016\packages\apple-rkwp-bundle\contracts\macos-capsule-openframe-contract.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\README.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\ios-xcode-project-layout.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\ios-rkwp-client-flow.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\ios-frame-guest-ui.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\ios-haptics-plan.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\ios-gesture-plan.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\ios-usb-test-plan.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\ios-sandbox-sources.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\iOS_SurfaceApp_Design.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\iOS_Haptics_Gesture_Plan.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\iOS_Xcode_USB_TestPlan.md',
    'src\Surfaces\RKWorkspace.Surface.iOS\iOS_Sandbox_ObjectSources.md',
    'release\ma016\handoff\iOS_START_HERE.md',
    'release\ma016\handoff\iOS_HapticMapping_CapsuleOpenFrame.md',
    'release\ma016\handoff\iPad_FrameCapsuleLayoutSpec.md',
    'release\ma016\handoff\iPhone_CompactCapsuleLayoutSpec.md',
    'release\ma016\handoff\iOS_iPadOS_FINAL_HANDOFF.md',
    'release\ma016\handoff\iOS_NEXT_REAL_IMPLEMENTATION_TASK.md',
    'release\ma016\handoff\WINDOWS_OWNER_HARDENING_TASK.md',
    'release\ma016\handoff\UWB_HARDWARE_NEXT_TASK.md',
    'release\ma016\handoff\DONGLE_MVP_NEXT_TASK.md',
    'release\ma016\handoff\PDF_RENDERER_FINAL_DECISION_TASK.md',
    'release\ma016\handoff\SECURITY_PRODUCTION_PATH_TASK.md',
    'release\ma016\handoff\UX_GLASS_EDGE_FOLLOWUP_TASK.md',
    'release\ma016\handoff\OBJECT_ADAPTER_ROADMAP_TASK.md',
    'release\ma016\config\ios-guest.sample.json',
    'release\ma016\config\windows-local.sample.json',
    'release\ma016\config\windows-to-mac.sample.json',
    'release\ma016\config\windows-to-ipad.sample.json',
    'release\ma016\config\uwb-simulation.sample.json',
    'release\ma016\config\dongle-prep.sample.json',
    'release\ma016\schemas\ios-capsule-contract.v0.1.json',
    'release\ma016\schemas\ios-openframe-contract.v0.1.json',
    'release\ma016\schemas\ios-no-file-ingress-sandbox-contract.v0.1.json',
    'release\ma016\reports\templates\no-file-ingress-ios-template.md',
    'Docs\Platform\iOS_iPadOS_SurfaceStarterKit.md',
    'Docs\Platform\iOS_XcodeProjectBootstrap.md',
    'Docs\Platform\iOS_RKWPClientFlow.md',
    'Docs\Platform\iOS_FramePresenter.md',
    'Docs\Platform\iOS_HapticsAndGesturePrototype.md',
    'Docs\Platform\iOS_NoFileIngressSandboxChecklist.md',
    'Docs\Platform\iOS_USBDeviceTestRunbook.md',
    'Docs\Platform\iOS_ReturnAndRecovery.md',
    'Docs\Platform\iOS_ShareExtensionObjectSource.md',
    'Docs\Platform\Android_SurfaceStarterKit.md',
    'Docs\Platform\Linux_SurfaceStarterKit.md',
    'Docs\Codex\CODEX_ONBOARDING.md',
    'Docs\Codex\CURRENT_CONTEXT.md',
    'Docs\Codex\PLATFORM_HANDOFF.md',
    'Docs\Codex\PLATFORM_STATUS.md',
    'Docs\Codex\PlatformTasks\macOS.md',
    'Docs\Codex\PlatformTasks\iOS_iPadOS.md',
    'Docs\Codex\PlatformTasks\Android.md',
    'Docs\Codex\PlatformTasks\Linux.md',
    'Spec\TestStrategy.md',
    'Spec\ProductPhilosophy.md',
    'Spec\UX.md',
    'Docs\Configuration\RKWorkspaceConfiguration.md',
    'Docs\Development\WindowsPdfFramePilot.md',
    'Docs\Development\MacGuestCompatibilityHarness.md',
    'contracts\macOS-guest\rkwp-macos-guest-contract-v0.1.json',
    'tests\Contract\RKWorkspace.MacGuest.Contracts\RKWorkspace.MacGuest.Contracts.csproj',
    'tests\Contract\RKWorkspace.MacGuest.Contracts\Program.cs',
    'tests\Unit\RKWorkspace.Protocol.Tests\Program.cs',
    'Docs\Development\iOSGuestCompatibilityHarness.md',
    'Docs\Development\WindowsOwnerForMac.md',
    'Docs\Frame\PdfFrameRendererDecision.md',
    'Docs\Frame\PdfRendererProductDecision.md',
    'Docs\Frame\PdfFrameRendererAbstraction.md',
    'Docs\Frame\PdfAnnotationChangeSet.md',
    'Docs\Frame\FrameCachePolicy.md',
    'src\Frame\RKWorkspace.Frame.Pdf\PdfLifecycleModels.cs',
    'Docs\Platform\WindowsAgentInstallationPlan.md',
    'Docs\Platform\WindowsServicePlan.md',
    'Docs\Platform\WindowsPermissions.md',
    'Docs\Platform\WindowsDevInstallerPlan.md',
    'Docs\Platform\macOSAgentInstallerPlan.md',
    'Docs\Platform\iOS_TestFlightAndDevInstallPlan.md',
    'Docs\Platform\Android_ImplementationPlan.md',
    'Docs\Platform\Linux_ImplementationPlan.md',
    'Docs\Operations\UpdateMechanismPlan.md',
    'Docs\Admin\LabSetupGuide.md',
    'release\MA016_READINESS_SUMMARY.md',
    'release\MA007_READINESS_SUMMARY.md',
    'release\MA009_READINESS_SUMMARY.md',
    'release\MA010_READINESS_SUMMARY.md',
    'release\MA011_READINESS_SUMMARY.md',
    'release\MA013_READINESS_SUMMARY.md',
    'release\handoff\WindowsToMac_MA008_Handoff.md',
    'release\handoff\WindowsToMac_MA009_Handoff.md',
    'release\handoff\macOS_Codex_MA009_FrameGuestSurface.md',
    'release\handoff\macOS_Codex_MA013_Bootstrap.md',
    'release\handoff\macOS_Codex_MA013_RKWPClient.md',
    'release\handoff\WindowsToMac_FirstRealTestGate.md',
    'release\handoff\iOS_XcodeProjectBootstrap_MA013.md',
    'release\handoff\WindowsToiPad_FirstRealTestGate.md',
    'release\handoff\iOS_iPadOS_Codex_MA009_SurfaceApp.md',
    'release\handoff\iOS_iPadOS_MA008_Handoff.md',
    'release\schema\rkwp-envelope-schema-v0.1.json',
    'config\samples\manual-ablage-map.sample.json',
    'config\samples\rkworkspace.sample.json',
    'config\samples\ablage.sample.json',
    'config\samples\rkwp-dev.sample.json',
    'config\samples\rkwp-dev-lan-owner.sample.json',
    'config\samples\rkwp-dev-lan-guest.sample.json',
    'config\samples\policy-critical.sample.json',
    'config\samples\policy-critical-infrastructure.sample.json',
    'src\Shell\RKWorkspace.Shell\Ablage\AblageProximityModel.cs',
    'src\Shell\RKWorkspace.Shell\Ablage\AblageProximityProviders.cs',
    'src\Shell\RKWorkspace.Shell\Ablage\GlassEdgeModel.cs',
    'src\Shell\RKWorkspace.Shell\Ablage\ManualAblageMap.cs',
    'src\Shell\RKWorkspace.Shell\Ablage\EdgeSelectionOverride.cs',
    'src\Shell\RKWorkspace.Shell\Ablage\WiFiPresenceProvider.cs',
    'src\Shell\RKWorkspace.Shell\Ablage\UwbProximityProvider.cs',
    'src\Surfaces\RKWorkspace.Surface.Abstractions\HapticModels.cs',
    'src\Surfaces\RKWorkspace.Surface.Abstractions\ISurfaceHapticsProvider.cs',
    'src\Frame\RKWorkspace.Frame.Pdf\OwnerGuestFrameStateUx.cs',
    'src\Frame\RKWorkspace.Frame.Pdf\PdfDocumentFrameState.cs',
    'src\Frame\RKWorkspace.Frame.Pdf\PdfFrameTiles.cs',
    'src\Frame\RKWorkspace.Frame.Pdf\PdfAnnotationChangeSet.cs',
    'src\Frame\RKWorkspace.Frame.Pdf\PdfTextExtraction.cs',
    'src\Frame\RKWorkspace.Frame.Pdf\PdfFrameValidation.cs',
    'src\Adapters\RKWorkspace.ObjectAdapter.Windows\WindowsObjectAdapters.cs',
    'src\Tools\RKWorkspace.WindowsObjectAdapterSmoke\RKWorkspace.WindowsObjectAdapterSmoke.csproj',
    'src\Tools\RKWorkspace.WindowsObjectAdapterSmoke\Program.cs',
    'src\Protocol\RKWorkspace.Protocol\Ownership\RkwpPolicyProfiles.cs',
    'src\Tools\RKWorkspace.RkwpPerfHarness\RKWorkspace.RkwpPerfHarness.csproj',
    'src\Tools\RKWorkspace.RkwpPerfHarness\Program.cs',
    'src\Tools\RKWorkspace.ConfigTool\Program.cs',
    'src\Tools\RKWorkspace.PolicyProfile\Program.cs',
    'src\Tools\RKWorkspace.RkwpDiagnostics\Program.cs',
    'src\Agents\RKWorkspace.Agent.Windows\Program.cs',
    'tools\run-windows-owner-for-mac.ps1',
    'tools\run-windows-pdf-owner-securedev.ps1',
    'tools\run-mac-guest-contract.ps1',
    'tools\export-rkwp-schema.ps1',
    'tools\init-dev-rkwp-identity.ps1',
    'tools\init-ablage-identity.ps1',
    'tools\run-rkwp-diagnostics.ps1',
    'tools\run-manual-map.ps1',
    'tools\run-policy-profile.ps1',
    'tools\run-rkwp-perf.ps1',
    'tools\run-rkwp-load.ps1',
    'tools\run-rkwp-lan-smoke.ps1',
    'tools\run-windows-securedev-pdf-e2e.ps1',
    'tools\run-rkwp-chaos.ps1',
    'tools\run-ma016-smoke.ps1',
    'tools\run-security-regression.ps1',
    'tools\run-windows-pdf-frame-pilot.ps1',
    'tools\run-windows-pdf-lifecycle-pilot.ps1',
    'tools\run-no-file-ingress-report.ps1',
    'tools\run-pilot-windows-to-mac-closed-pdf.ps1',
    'tools\run-pilot-windows-to-mac-open-pdf.ps1',
    'tools\run-pilot-windows-to-ipad-closed-pdf.ps1',
    'tools\run-pilot-windows-to-ipad-open-pdf.ps1',
    'tools\run-pilot-windows-all-pdf-lifecycle.ps1',
    'tools\run-cross-device-session-monitor.ps1',
    'tools\export-cross-device-diagnostics.ps1',
    'tools\export-cross-device-audit.ps1',
    'tools\run-cross-device-security-regression.ps1',
    'tools\run-cross-device-policy-regression.ps1',
    'tools\run-ma016-pilot-lab.ps1',
    'tools\configure-ma016-pilot.ps1',
    'tools\export-ma016-pilot-report.ps1',
    'tools\record-ma016-feedback.ps1',
    'tools\export-ma016-feedback-report.ps1',
    'tools\cleanup-ma016-pilot.ps1',
    'tools\run-ma016-repeatability.ps1',
    'tools\export-ma016-performance-baseline.ps1',
    'tools\package-ma016-owner-test.ps1',
    'tools\test-context-pack-no-secrets.ps1',
    'tools\redact-local-config.ps1',
    'tools\clean-build-artifacts.ps1',
    'tools\clean-pilot-artifacts.ps1',
    'tools\check-ma016-final-status.ps1',
    'tools\run-ma017-smoke.ps1',
    'tools\run-ma017-windows-pdf-pilot.ps1',
    'tools\run-ma017-security-policy-pilot.ps1',
    'tools\run-windows-object-adapter.ps1',
    'tools\run-config-tool.ps1',
    'tools\package-windows-dev.ps1',
    'tools\run-windows-agent-dev.ps1',
    'tools\run-mac-guest-compat.ps1',
    'tools\run-ios-guest-compat.ps1'
)

$files | ForEach-Object { Copy-ContextFile $_ }

git -C $root status --short --branch | Set-Content -Path (Join-Path $staging 'git-status.txt') -Encoding UTF8
git -C $root log --oneline -30 | Set-Content -Path (Join-Path $staging 'git-log-last-30.txt') -Encoding UTF8
git -C $root ls-files | Where-Object { $_ -notmatch '(^|/)(bin|obj)/' } | Set-Content -Path (Join-Path $staging 'project-tree.txt') -Encoding UTF8

@'
.\tools\run-tests.ps1
.\tools\run-studio.ps1 -SmokeTest
.\tools\run-rkwp-tests.ps1
.\tools\run-pdf-frame-smoke.ps1
.\tools\run-windows-owner-for-mac.ps1 -InfoOnly
.\tools\run-rkwp-diagnostics.ps1 -SmokeTest
.\tools\run-rkwp-perf.ps1 -SmokeTest
.\tools\run-rkwp-load.ps1 -SmokeTest
.\tools\run-rkwp-lan-smoke.ps1
.\tools\run-windows-securedev-pdf-e2e.ps1 -SmokeTest
.\tools\run-rkwp-chaos.ps1 -SmokeTest
.\tools\run-ma016-smoke.ps1 -SkipHeavy
.\tools\test-context-pack-no-secrets.ps1
.\tools\redact-local-config.ps1 -SmokeTest
.\tools\clean-build-artifacts.ps1 -DryRun
.\tools\clean-pilot-artifacts.ps1 -DryRun
.\tools\check-ma016-final-status.ps1
.\tools\run-windows-pdf-frame-pilot.ps1 -SmokeTest
.\tools\run-windows-pdf-frame-pilot.ps1 -SmokeTest -UseGlassEdge -UseUwbSim -UwbProfile MovingCloser -PlaySequence
.\tools\run-windows-pdf-frame-pilot.ps1 -SmokeTest -UseGlassEdge -UseProximityFusion -UwbProfile PassingBy -PlaySequence
.\tools\run-windows-pdf-lifecycle-pilot.ps1 -SmokeTest -ClosedPdf
.\tools\run-windows-pdf-lifecycle-pilot.ps1 -SmokeTest -OpenPdf
.\tools\run-ma017-windows-pdf-pilot.ps1 -SmokeTest
.\tools\run-ma017-security-policy-pilot.ps1 -SmokeTest
.\tools\run-no-file-ingress-report.ps1
.\tools\run-cross-device-session-monitor.ps1 -SmokeTest
.\tools\export-cross-device-diagnostics.ps1 -SmokeTest
.\tools\export-cross-device-audit.ps1 -SmokeTest
.\tools\run-cross-device-security-regression.ps1 -SmokeTest
.\tools\run-cross-device-policy-regression.ps1 -SmokeTest
.\tools\run-ma016-pilot-lab.ps1 -SmokeTest
.\tools\package-ma016-owner-test.ps1 -SmokeTest
.\tools\run-config-tool.ps1 -SmokeTest
.\tools\run-windows-agent-dev.ps1 -SmokeTest
.\tools\run-mac-guest-compat.ps1 -SmokeTest
.\tools\run-ios-guest-compat.ps1 -SmokeTest
.\tools\export-codex-context.ps1
'@ | Set-Content -Path (Join-Path $staging 'test-commands.txt') -Encoding UTF8

@'
Windows: RKWP Frame Presenter an Native Glass Edge anbinden.
Windows: Baue sichtbaren Windows PDF Owner/Guest Pilot weiter aus und stabilisiere Frame UI.
macOS: Baue macOS Frame Guest Surface mit RKWP DevLan Client.
iOS/iPadOS: Baue iPad/iPhone RK Workspace Surface App, die RKWP Frame anzeigen kann, Haptik unterstuetzt und No File Ingress respektiert.
Android: Baue Android Frame Guest Surface mit RKWP DevTransport.
Linux: Baue Linux Frame Guest Surface unter Wayland/X11-Beruecksichtigung.
Hardware: Definiere Dongle Hardware MVP fuer Ablage-Anker mit BLE/UWB/USB.
'@ | Set-Content -Path (Join-Path $staging 'platform-next-steps.txt') -Encoding UTF8

Compress-Archive -Path (Join-Path $staging '*') -DestinationPath $zipPath -Force
Copy-Item -LiteralPath $zipPath -Destination $latestZipPath -Force
Remove-Item -LiteralPath $staging -Recurse -Force

Write-Host 'RK Workspace Codex Context Export'
Write-Host "Output: $zipPath"
Write-Host "Latest: $latestZipPath"
Write-Host 'RESULT: SUCCESS'
